let imagemCenario;
let imagemPersonagem;
let imagemInimigo;
let imagemGameOver;
let cenario;
let imagemTelaInicial;
let fonteTelaInicial;
let somDoJogo;
let somPulo;
let personagem;
let inimigoG;
let inimigoT;
let inimigoV;
let pontuacao;
let imagemCoracao;
let vida;
let jogo;
let cenaAtual = 'telaInicial';
let cenas;
let telaInicial;
let botaoGerenciador;
const inimigos = [];
let fita;